# Generated by Django 3.2.9 on 2022-04-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='company.employee'),
        ),
    ]
