# Generated by Django 3.2.9 on 2022-04-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='company',
        ),
        migrations.AddField(
            model_name='location',
            name='branch',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='company.branch', verbose_name='Branch'),
            preserve_default=False,
        ),
    ]
