# Generated by Django 3.2.9 on 2022-04-30 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20220426_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='client',
        ),
        migrations.RemoveField(
            model_name='month',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='month',
            name='start_month',
        ),
        migrations.AddField(
            model_name='month',
            name='month',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('Edited', 'Edited')], default='Pending', max_length=250),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='company.client', verbose_name='Client')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='company.month', verbose_name='Month')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
