# Generated by Django 3.2.9 on 2022-05-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20220430_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
