# Generated by Django 3.2.9 on 2022-05-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20220502_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
