# Generated by Django 3.2.9 on 2022-05-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20220507_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
