# Generated by Django 3.2.9 on 2022-05-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_alter_company_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
