# Generated by Django 3.2.9 on 2022-05-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_alter_month_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
