# Generated by Django 3.2.9 on 2022-06-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_alter_month_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
