# Generated by Django 3.2.9 on 2022-06-18 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_alter_month_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
