# Generated by Django 3.2.9 on 2022-06-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_alter_employee_join_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['id'], 'verbose_name': 'Month', 'verbose_name_plural': 'Months'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['id'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['id'], 'verbose_name': 'Week', 'verbose_name_plural': 'Weeks'},
        ),
    ]
