# Generated by Django 3.2.9 on 2022-06-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_auto_20220618_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='report_deadline',
            field=models.IntegerField(default=14),
        ),
    ]
