# Generated by Django 4.0.4 on 2022-04-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
