# Generated by Django 3.2.9 on 2022-04-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Staff', 'Staff'), ('Manager', 'Manager'), ('Team Lead', 'Team Lead')], default='Staff', max_length=250),
        ),
    ]
