# Generated by Django 3.2.9 on 2022-07-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220507_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
