# Generated by Django 3.2.9 on 2022-07-24 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_trial_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to=settings.AUTH_USER_MODEL),
        ),
    ]
